#!/bin/bash

# don't accept bsync commands unless repo is already initialized
if [ ! -d ".bsync/" ] && [ "$1" != "init" ]; then
    echo "Not a bsync repository"
    exit 1
fi

case $1 in
    # initialize repo
    init)
    # don't re-init repo
    if [ -d ".bsync/" ]; then
        echo "Already initialized bsync repository"
    
    # create config file and place name on first line
    else
        mkdir .bsync
        cd .bsync
        touch config
        #echo $2 >> config ##don't give name local repository
        touch files
        sha1sum files > metafile
        #echo "Initialized bsync repository `head -n 1 config` in `pwd`"
        echo "Initialized bsync repository in `pwd`"
    fi
    ;;

    remote)
    case $2 in
        add)
        cd .bsync
        if grep -q "=$4" config; then
            echo "$4 already saved as `grep "=$4" config | cut -d '=' -f 1`"
        elif grep -q "$3=" config; then
            echo "$3 already assigned to `grep "$3=" config | cut -d '=' -f 2`"
        else
            # test if remote repo exists
            #   (removed feature)
            #RHOST=`echo $3 | cut -d ':' -f 1`
            #RPATH=`echo $3 | cut -d ':' -f 2`
            #if RNAME=`ssh -q $RHOST head -n 1 "$RPATH/.bsync/config" 2>/dev/null`; then
            #    echo "$RNAME=$3" >> config
            #    echo "$RNAME->$3"
            #else
            #    echo "No bsync repository at $3"
            #fi

            echo "$3=$4" >> config
        fi
        ;;
    esac
    ;;
            
esac

# Copyright © 2016 Brian Pomerantz. All Rights Reserved.
